# Rustfmt configuration for Matcha Backend
# Format: https://rust-lang.github.io/rustfmt/

# Indentation
tab_spaces = 4
indent_style = "Spaces"

# Line length
max_width = 100

# Function formatting
fn_call_width = 100

# Control flow
control_brace_style = "AlwaysNextLine"
else_trailing_comma = false
if_trailing_comma = false
match_arm_leading_pipes = "Never"
match_arm_wrapping = "Preserve"

# Comments
comment_width = 100
wrap_comments = true

# Other
edition = "2021"
newline_style = "Unix"
merge_derives = true
use_small_heuristics = "Default" 