# Rustfmt configuration for Matcha Backend
# Format: https://rust-lang.github.io/rustfmt/

# Indentation
tab_spaces = 4

# Line length
max_width = 100

# Function formatting
fn_call_width = 100

# Control flow
match_arm_leading_pipes = "Never"

# Other
edition = "2021"
newline_style = "Unix"
merge_derives = true
use_small_heuristics = "Default" 